# Generated by Django 5.1 on 2024-09-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0003_alter_doctor_options_alter_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(verbose_name="Дата записи"),
        ),
    ]
