# Generated by Django 4.2.2 on 2024-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0006_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Static",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.TextField(verbose_name="О компании")),
                (
                    "history",
                    models.TextField(blank=True, null=True, verbose_name="История"),
                ),
                (
                    "values",
                    models.TextField(blank=True, null=True, verbose_name="Ценности"),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "map",
                    models.ImageField(
                        blank=True, null=True, upload_to="diagnostics/maps"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
            ],
        ),
    ]
