# Generated by Django 4.2.2 on 2024-09-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0007_static"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="static",
            options={"verbose_name": "Статика", "verbose_name_plural": "Статика"},
        ),
    ]
