# Generated by Django 4.2.2 on 2024-09-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0008_alter_static_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="static",
            name="updated_at",
        ),
    ]
